2020-02-02 14:51:04,940 INFO [__init__.py:6] - [测试日志信息]
2020-02-02 15:03:46,034 INFO [__init__.py:6] - [测试日志信息]
2020-02-02 15:03:46,544 INFO [login_test.py:22] - [登录成功的数据:]
2020-02-02 15:05:43,832 INFO [__init__.py:6] - [测试日志信息]
2020-02-02 15:05:44,224 INFO [login_test.py:22] - [登录成功的数据:]
2020-02-02 15:07:15,395 INFO [__init__.py:6] - [测试日志信息]
2020-02-02 15:07:15,613 INFO [login_test.py:22] - [登录成功的数据: {'success': True, 'code': 10000, 'message': '操作成功！', 'data': 'f5399360-b963-4bc5-95f1-42fd2d2ef56c'}]
2020-02-02 15:10:05,645 INFO [__init__.py:6] - [测试日志信息]
2020-02-02 15:10:05,865 INFO [login_test.py:22] - [登录成功的数据: {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '116be2a9-aad9-4629-a153-a3b6c892eddd'}]
2020-02-02 15:10:21,831 INFO [__init__.py:6] - [测试日志信息]
2020-02-02 15:10:22,041 INFO [login_test.py:22] - [登录成功的数据: {'success': True, 'code': 10000, 'message': '操作成功！', 'data': 'cb4a61c4-5fc2-43e0-afc6-a7aa5cc82e0d'}]
2020-02-02 15:10:51,648 INFO [__init__.py:6] - [测试日志信息]
2020-02-02 15:10:51,861 INFO [login_test.py:22] - [登录成功的数据: {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '08657b81-eb7e-4805-9613-f69c03a7b4ef'}]
2020-02-02 15:20:31,048 INFO [__init__.py:6] - [测试日志信息]
2020-02-02 15:20:31,273 INFO [login_test.py:23] - [登录成功的数据: {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '7f691319-367c-480e-a300-f65457976a68'}]
2020-02-02 15:24:21,947 INFO [__init__.py:6] - [测试日志信息]
2020-02-02 15:24:22,374 INFO [login_test.py:36] - [用户不存在: {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}]
2020-02-02 15:59:52,153 INFO [__init__.py:6] - [测试日志信息]
2020-02-02 15:59:52,459 INFO [login_test.py:23] - [登录成功的数据: {'success': True, 'code': 10000, 'message': '操作成功！', 'data': 'e06a4696-7496-4c2d-9eec-4251809ec643'}]
2020-02-02 15:59:52,522 INFO [login_test.py:36] - [用户不存在: {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}]
2020-02-02 15:59:52,580 INFO [login_test.py:66] - [密码错误: {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '48310c75-ed54-4e79-9e1c-14678b06e062'}]
2020-02-02 15:59:52,636 INFO [login_test.py:48] - [密码错误: {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}]
2020-02-02 15:59:52,689 INFO [login_test.py:42] - [密码错误: {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}]
2020-02-02 15:59:52,743 INFO [login_test.py:60] - [密码错误: {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}]
2020-02-02 15:59:52,810 INFO [login_test.py:54] - [密码错误: {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}]
2020-02-02 16:00:05,905 INFO [__init__.py:6] - [测试日志信息]
2020-02-02 16:00:06,406 INFO [login_test.py:23] - [登录成功的数据: {'success': True, 'code': 10000, 'message': '操作成功！', 'data': 'aa3db90d-17ae-4d3e-b393-c0d9a5c57e93'}]
2020-02-02 16:00:06,475 INFO [login_test.py:36] - [用户不存在: {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}]
2020-02-02 16:00:06,587 INFO [login_test.py:66] - [密码错误: {'success': True, 'code': 10000, 'message': '操作成功！', 'data': '57d8b7d8-190f-44de-ab74-960e6713ecb9'}]
2020-02-02 16:00:06,648 INFO [login_test.py:48] - [密码错误: {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}]
2020-02-02 16:00:06,715 INFO [login_test.py:42] - [密码错误: {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}]
2020-02-02 16:00:06,788 INFO [login_test.py:60] - [密码错误: {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}]
2020-02-02 16:00:06,850 INFO [login_test.py:54] - [密码错误: {'success': False, 'code': 20001, 'message': '用户名或密码错误', 'data': None}]
